# PowerJetpack - Jetpacks!
# Criado por MrPowerGamerBR - mrpowergamerbr.blogspot.com
# SparklyPower: sparklypower.melhorserver.net
Jetpack:
    Jetpacks:
        VIP:
            Permissao: PowerJetpack.VIP
            Fuel: DIRT
            Quantidade: 1
        Membros:
            Permissao: PowerJetpack.Membro
            Fuel: COAL
            Quantidade: 1
    # Item da Jetpack, óbviamente precisa ser algum tipo de peitoral
    Jetpack: CHAINMAIL_CHESTPLATE
    # Tempo de Verificação para remover o combustível do Player (Recomendado: 3)
    VerifyTime: 3
    # Mundos que não pode usar a Jetpack
    MundosBloqueados:
    - world_the_end
    
Mensagens:
    VoandoJetpack: "&aVocê agora está voando!"
    ChaoJetpack: "&aVocê agora não está voando!"
    SemPerm: "&cSem &4Permissão&c!"
    SemCombustivel: "&cVocê não tem carvões para poder voar!"
    NaoPodeMundo: "&cVocê não pode usar a Jetpack neste Mundo!"
    TirouJetpack: "&cVocê tirou a sua Jetpack, fazendo você cair no chão..."
    Woosh: "&6Woosh&e!"
    Combustivel: "&cSeu Combustível acabou!"